robot2/robot2:
    slam_toolbox:
      ros__parameters:
        # Plugin params
        solver_plugin: solver_plugins::CeresSolver
        ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
        ceres_preconditioner: SCHUR_JACOBI
        ceres_trust_strategy: LEVENBERG_MARQUARDT
        ceres_dogleg_type: TRADITIONAL_DOGLEG
        ceres_loss_function: None

        # === PARAMETRI CHIAVE MODIFICATI ===
        odom_frame: robot2/robot2/odom
        map_frame: robot2/robot2/map
        base_frame: robot2/robot2/base_footprint
        scan_topic: scan         # questo deve rimanere invariato (scan) per iscriversi al topic /robot2/scan
        use_sim_time: true       
        map_name: /robot2/robot2/map  # IMPORTANTE :  questo permette di pubblicare la mappa su /robot2/robot2/map
        # Parametri di mapping
        use_map_saver:  true 
        mode: mapping
        debug_logging: false
        throttle_scans: 1
        transform_publish_period: 0.02
        map_update_interval: 5.0
        resolution: 0.05
        min_laser_range: 0.12
        max_laser_range: 3.5
        minimum_time_interval: 0.5
        transform_timeout: 0.2
        tf_buffer_duration: 30.0
        stack_size_to_use: 40000000
        enable_interactive_mode: true

        # Parametri di scan matching
        use_scan_matching: true
        use_scan_barycenter: true
        minimum_travel_distance: 0.5
        minimum_travel_heading: 0.5
        scan_buffer_size: 10  # PROVATO AD AUMENTARE MA NON HA EFFETTO
        scan_buffer_maximum_scan_distance: 10.0
        link_match_minimum_response_fine: 0.1
        link_scan_maximum_distance: 1.5
        loop_search_maximum_distance: 3.0

        # Parametri di loop closing
        do_loop_closing: true
        loop_match_minimum_chain_size: 10
        loop_match_maximum_variance_coarse: 3.0
        loop_match_minimum_response_coarse: 0.35
        loop_match_minimum_response_fine: 0.45
        
        # Parametri di correlazione
        correlation_search_space_dimension: 0.5
        correlation_search_space_resolution: 0.01
        correlation_search_space_smear_deviation: 0.1
        
        # Parametri di ricerca loop
        loop_search_space_dimension: 8.0
        loop_search_space_resolution: 0.05
        loop_search_space_smear_deviation: 0.03

        # Parametri di penalità
        distance_variance_penalty: 0.5
        angle_variance_penalty: 1.0
        fine_search_angle_offset: 0.00349
        coarse_search_angle_offset: 0.349
        coarse_angle_resolution: 0.0349
        minimum_angle_penalty: 0.9
        minimum_distance_penalty: 0.5
        use_response_expansion: true
        min_pass_through: 2
        occupancy_threshold: 0.1

